### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'run'

### ISSUE THREAD

**Issue by chendwww** [aronweiler/assistant#23] opened 2023-09-25 02:00 UTC
![image](https://github.com/aronweiler/assistant/assets/25785677/e3f208ed-e407-46a8-9543-e31bd3e80616)

We just try the system and get error when ask document questions, any ideas how to fix it?

**Comment by aronweiler** [comment] 2023-09-25 16:19
So it looks like it can't find a destination for the query... this means that the configuration is probably bad, or that some of the prerequisites are not set up.

Usually you can find the answer to this in the logs, when it is initially loading the destination AIs.  You might see an "ERROR loading document destination" or something along those lines, that would tell you what is happening.

If you're running this in VS Code for example, you'll see a bunch of log items like this:
```
INFO:root:Interaction ID: cf73c145-0c71-47ea-bdc8-13a4e8823817 already exists for user 1, needs summary: False
INFO:root:Conversation memory created for interaction cf73c145-0c71-47ea-bdc8-13a4e8823817, with max token limit 8192
INFO:root:Interaction ID: cf73c145-0c71-47ea-bdc8-13a4e8823817 already exists for user 1, needs summary: False
INFO:root:Conversation memory created for interaction cf73c145-0c71-47ea-bdc8-13a4e8823817, with max token limit 6096
...
```
Those are where it's loading the destination AIs... if something has gone wrong, you'll see an error in there that can likely point you to the issue.

Let me know what you can see in there, and I can help you troubleshoot it.

**Comment by chendwww** [comment] 2023-09-26 00:47
Thank you for reply, we find the log, please check how to fix it


```
Got mismatched input_variables. Expected: {'loaded_documents', 'input', 'agent_scratchpad', 'chat_history', 'system_information'}. Got: ['input', 'loaded_documents', 'agent_chat_history', 'agent_scratchpad', 'system_information'] (type=value_error)
2023-09-25 06:40:13.195 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/1_General_AI.py", line 734, in <module>
    streamlit_ui.handle_chat(col1)
  File "/app/pages/1_General_AI.py", line 605, in handle_chat
    result = general_ai_instance.query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/ai/request_router.py", line 103, in query
    return self._route_response(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/ai/request_router.py", line 120, in _route_response
    response = destination.instance.run(
               ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'run'
INFO:root:Interaction ID: a1c3f8f7-d611-45c2-8161-a03ca51e670c already exists for user 1, needs summary: False
INFO:root:Conversation memory created for interaction a1c3f8f7-d611-45c2-8161-a03ca51e670c, with max token limit 8192
INFO:root:Interaction ID: a1c3f8f7-d611-45c2-8161-a03ca51e670c already exists for user 1, needs summary: False
INFO:root:Conversation memory created for interaction a1c3f8f7-d611-45c2-8161-a03ca51e670c, with max token limit 6096
INFO:root:Interaction ID: a1c3f8f7-d611-45c2-8161-a03ca51e670c already exists for user 1, needs summary: False
INFO:root:Conversation memory created for interaction a1c3f8f7-d611-45c2-8161-a03ca51e670c, with max token limit 4096
INFO:root:Interaction ID: a1c3f8f7-d611-45c2-8161-a03ca51e670c already exists for user 1, needs summary: False






INFO:root:Conversation memory created for interaction a1c3f8f7-d611-45c2-8161-a03ca51e670c, with max token limit 2048
ERROR:root:Error creating an instance of DocumentsAI class: 1 validation error for ChatPromptTemplate
__root__
  Got mismatched input_variables. Expected: {'loaded_documents', 'input', 'agent_scratchpad', 'chat_history', 'system_information'}. Got: ['input', 'loaded_documents', 'agent_chat_history', 'agent_scratchpad', 'system_information'] (type=value_error)
INFO:root:Interaction ID: a1c3f8f7-d611-45c2-8161-a03ca51e670c already exists for user 1, needs summary: False
INFO:root:Conversation memory created for interaction a1c3f8f7-d611-45c2-8161-a03ca51e670c, with max token limit 500
ERROR:root:Error creating an instance of CodeAI class: CodeTool.__init__() got an unexpected keyword argument 'destination'
ERROR:root:Error creating an instance of SpreadsheetsAI class: No module named 'src.ai.destinations.spreadsheets'
INFO:root:Interaction ID: a1c3f8f7-d611-45c2-8161-a03ca51e670c already exists for user 1, needs summary: False
INFO:root:Conversation memory created for interaction a1c3f8f7-d611-45c2-8161-a03ca51e670c, with max token limit 2048
ERROR:root:Error creating an instance of CurrentEventsAI class: 1 validation error for ChatPromptTemplate
```

**Comment by aronweiler** [comment] 2023-09-26 03:01
Ok, I made some changes and merged them with main... try pulling the latest, and see if it works better now :)

**Comment by chendwww** [comment] 2023-09-27 00:19
Thank you. Is the docker updated too? We install the project via the docker compose

**Comment by aronweiler** [comment] 2023-09-27 04:36
I just pushed the updated docker image!  Let me know if that works.

**Comment by chendwww** [comment] 2023-09-27 06:38
Hello, we got new error:

`2023-09-27 06:25:09.061 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/3_Software_Development_AI.py", line 539, in <module>
    general_ui.load_configuration()
  File "/app/pages/3_Software_Development_AI.py", line 67, in load_configuration
    st.session_state.config = SoftwareDevelopmentConfigurationLoader.from_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/configuration/assistant_configuration.py", line 115, in from_file
    return SoftwareDevelopmentConfigurationLoader.from_dict(config_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/configuration/assistant_configuration.py", line 129, in from_dict
    design_decision_generator=DesignDecisionGenerator(design_decisions_data),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/configuration/assistant_configuration.py", line 60, in __init__
    self.model_configuration = ModelConfiguration(**design_decision_configuration['model_configuration'])
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'model_configuration'
INFO:alembic.runtime.migration:Context impl PostgresqlImpl.
INFO:alembic.runtime.migration:Will assume transactional DDL.`

When we ask something about the document we uploaded, we get an blank answer like this:

![image](https://github.com/aronweiler/assistant/assets/25785677/238c923e-f91f-4048-9098-efc148c63073)

**Comment by aronweiler** [comment] 2023-09-29 04:30
So @chendwww, I can get this to reproduce, and I am investigating.

**Closed** 2023-09-29 08:42 UTC
Labels: bug

**Comment by aronweiler** [comment] 2023-09-29 08:47
@chendwww, I believe this is fixed for now... there is a bug that appears in langchain, which seems to be newly introduced- until a fix is in, I have a fallback solution that is implemented.  

You should be able to pull the latest image and it should not give you blank responses anymore.
